version: '3.8'

services:
  api:
    image: mcr.microsoft.com/dotnet/aspnet:8.0
    container_name: product_api
    ports:
      - "80:80"
      - "443:443"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ./app:/app
    depends_on:
      - db
    networks:
      - internal_network

  db:
    image: postgres:16
    container_name: product_database
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: qazwsx123!
    volumes:
      - ./data:/var/lib/postgresql/data
    networks:
      - internal_network

networks:
  internal_network:
    driver: bridge
