// <auto-generated />
using Infrastructure.Database.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastructure.Database.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240103144432_CreateProducts")]
    partial class CreateProducts
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AvailableQuantity")
                        .HasColumnType("INTEGER")
                        .HasColumnName("AvailableQuantity");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("VARCHAR")
                        .HasColumnName("Description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("VARCHAR")
                        .HasColumnName("Name");

                    b.Property<decimal>("Price")
                        .HasColumnType("DECIMAL")
                        .HasColumnName("Price");

                    b.HasKey("Id");

                    b.ToTable("Product", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AvailableQuantity = 100,
                            Description = "Powerful laptop with high-performance processor",
                            Name = "Laptop",
                            Price = 1299.99m
                        },
                        new
                        {
                            Id = 2,
                            AvailableQuantity = 200,
                            Description = "Latest smartphone with advanced camera features",
                            Name = "Smartphone",
                            Price = 899.99m
                        },
                        new
                        {
                            Id = 3,
                            AvailableQuantity = 50,
                            Description = "Noise-canceling headphones for immersive audio experience",
                            Name = "Headphones",
                            Price = 149.99m
                        },
                        new
                        {
                            Id = 4,
                            AvailableQuantity = 30,
                            Description = "Fitness tracker and smartwatch with health monitoring",
                            Name = "Smartwatch",
                            Price = 199.99m
                        },
                        new
                        {
                            Id = 5,
                            AvailableQuantity = 20,
                            Description = "Professional-grade camera for photography enthusiasts",
                            Name = "Camera",
                            Price = 1499.99m
                        },
                        new
                        {
                            Id = 6,
                            AvailableQuantity = 80,
                            Description = "Bluetooth speaker with premium sound quality",
                            Name = "Wireless Speaker",
                            Price = 79.99m
                        },
                        new
                        {
                            Id = 7,
                            AvailableQuantity = 10,
                            Description = "Next-gen gaming console for immersive gaming experience",
                            Name = "Gaming Console",
                            Price = 499.99m
                        },
                        new
                        {
                            Id = 8,
                            AvailableQuantity = 15,
                            Description = "Ultra HD Smart TV with stunning picture quality",
                            Name = "4K TV",
                            Price = 799.99m
                        },
                        new
                        {
                            Id = 9,
                            AvailableQuantity = 5,
                            Description = "High-performance drone with 4K camera for aerial photography",
                            Name = "Drone",
                            Price = 999.99m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
